### ISSUE TITLE
Duncan: improper conditional rendering

### ISSUE THREAD

**Issue by ccdlt** [TheHackMasters/FECapstone#94]
https://github.com/TheHackMasters/FECapstone/blob/4b897c9b472fdc3012daa388f6626a3d9e62f4f5/Client/SRC/Components/DOverview/Checkbox.jsx#L26-L37

While this works, it is not best practice to conditionally render using css. Refer to the React docs here:
[conditional rendering](https://reactjs.org/docs/conditional-rendering.html)

**Comment by Thistleman** [comment]
Removed CSS conditional rendering and updated logic to conditionally render the elements
