### ISSUE TITLE
Norman: mixed styling

### ISSUE THREAD

**Issue by ccdlt** [TheHackMasters/FECapstone#95]
https://github.com/TheHackMasters/FECapstone/blob/4b897c9b472fdc3012daa388f6626a3d9e62f4f5/Client/SRC/Components/RatingsNReviews/ratings/BarGraph/Bar.jsx#L16

Try to keep to either inline styles or styled-components instead of mixing the two

**Comment by itsnormsyo** [comment]
This inline style prop dictates the size of each bar using props.

**Comment by itsnormsyo** [comment]
resolved!
