### ISSUE TITLE
Norman: unused classNames

### ISSUE THREAD

**Issue by ccdlt** [TheHackMasters/FECapstone#96]
https://github.com/TheHackMasters/FECapstone/blob/4b897c9b472fdc3012daa388f6626a3d9e62f4f5/Client/SRC/Components/RatingsNReviews/ratings/BarGraph/BarGraph.jsx#L38

Okay to remove if you are not using classNames for styling

**Comment by itsnormsyo** [comment]
Changed! Thank you
